const notice = document.querySelector('#notice');
const language = localStorage.getItem('language') || 'cs';
const text = (cs, en) => language === 'en' ? en : cs;
const status = (value) => `<span class="badge status-badge" title="${escapeHtml(value)}">${value === 'Nová' ? '🆕 ' : '✨ '}${escapeHtml(value === 'Nová' ? text('Nová', 'New') : value)}</span>`;
function applyLanguage() { const headerLink = document.querySelector('.app-header a:last-child'); headerLink.textContent = text('← Služby', '← Services'); document.querySelector('.logout').textContent = text('Odhlásit se', 'Log out'); document.querySelector('.dashboard-head .eyebrow').textContent = text('zákaznický panel', 'customer panel'); document.querySelector('#account h1').childNodes[0].textContent = text('Vítejte, ', 'Welcome, '); const panels = document.querySelectorAll('.panel'); panels[0].querySelector('.eyebrow').textContent = text('nová objednávka', 'new order'); panels[0].querySelector('h2').textContent = text('Co pro vás připravíme?', 'What can we prepare?'); panels[0].querySelector('label').childNodes[0].textContent = text('Služba', 'Service'); panels[0].querySelectorAll('label')[1].childNodes[0].textContent = text('Popis objednávky', 'Order details'); panels[0].querySelector('textarea').placeholder = text('Napište, co přesně potřebujete…', 'Tell us exactly what you need…'); panels[0].querySelector('.button').textContent = text('Odeslat objednávku →', 'Send order →'); panels[1].querySelector('.eyebrow').textContent = text('vaše objednávky', 'your orders'); panels[1].querySelector('h2').textContent = text('Přehled zakázek', 'Order overview'); document.querySelector('#admin-link').textContent = text('Otevřít administraci →', 'Open administration →'); }
const languageButton = document.createElement('button'); languageButton.className = 'logout'; languageButton.textContent = language === 'en' ? '🇨🇿 Česky' : '🇬🇧 English'; languageButton.style.marginRight = '8px'; document.querySelector('.app-header').append(languageButton); languageButton.addEventListener('click', () => { localStorage.setItem('language', language === 'en' ? 'cs' : 'en'); window.location.reload(); });
document.head.insertAdjacentHTML('beforeend', '<style>.status-badge{display:inline-block;animation:status-pop 1.8s ease-in-out infinite}@keyframes status-pop{50%{transform:translateY(-2px) scale(1.06);filter:brightness(1.08)}}</style>');
const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[c]));
const date = (value) => new Intl.DateTimeFormat('cs-CZ', { dateStyle: 'medium' }).format(new Date(value));
async function request(url, options) { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error); return data; }
function renderOrders(orders) { document.querySelector('#orders').innerHTML = orders.length ? orders.map((order) => `<article class="order"><div class="order-top"><span>${escapeHtml(order.service)}</span>${status(order.status)}</div><p>${escapeHtml(order.details)}</p><div class="order-footer"><small>${text('Vytvořeno', 'Created')} ${date(order.createdAt)}</small><button class="delete-order" type="button" data-order-id="${escapeHtml(order.id)}">${text('Odstranit', 'Delete')}</button></div></article>`).join('') : `<p class="lead">${text('Zatím nemáte žádnou objednávku.', 'You have no orders yet.')}</p>`; }
async function load() { try { const me = await request('/api/me'); document.querySelector('#email').textContent = me.user.email; if (me.user.role === 'admin') document.querySelector('#admin-link').classList.remove('hidden'); renderOrders((await request('/api/orders')).orders); } catch { window.location.href = 'auth.html'; } }
document.querySelector('#order-form').addEventListener('submit', async (event) => { const form = event.currentTarget; event.preventDefault(); try { await request('/api/orders', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(Object.fromEntries(new FormData(form))) }); notice.textContent = 'Objednávka byla odeslána.'; notice.className = 'notice success'; form.reset(); const orders = await request('/api/orders'); renderOrders(orders.orders); } catch (error) { notice.textContent = error.message; notice.className = 'notice error'; } });
document.querySelector('#orders').addEventListener('click', async (event) => { const button = event.target.closest('.delete-order'); if (!button || !confirm(text('Opravdu chcete tuto objednávku odstranit?', 'Do you really want to delete this order?'))) return; try { await request(`/api/orders/${encodeURIComponent(button.dataset.orderId)}`, { method:'DELETE' }); notice.textContent = text('Objednávka byla odstraněna.', 'Order deleted.'); notice.className = 'notice success'; renderOrders((await request('/api/orders')).orders); } catch (error) { notice.textContent = error.message; notice.className = 'notice error'; } });
document.querySelector('#logout').addEventListener('click', async () => { await fetch('/api/logout', { method:'POST' }); window.location.href = 'index.html'; });
applyLanguage(); load();
