const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[c]));
const language = localStorage.getItem('language') || 'cs';
const text = (cs, en) => language === 'en' ? en : cs;
const status = (value) => `<span class="badge status-badge">${value === 'Nová' ? '🆕 ' : '✨ '}${escapeHtml(value === 'Nová' ? text('Nová', 'New') : value)}</span>`;
const languageButton = document.createElement('button'); languageButton.className = 'logout'; languageButton.textContent = language === 'en' ? '🇨🇿 Česky' : '🇬🇧 English'; languageButton.style.marginRight = '8px'; document.querySelector('.app-header').append(languageButton); languageButton.addEventListener('click', () => { localStorage.setItem('language', language === 'en' ? 'cs' : 'en'); window.location.reload(); });
document.head.insertAdjacentHTML('beforeend', '<style>.status-badge{display:inline-block;animation:status-pop 1.8s ease-in-out infinite}@keyframes status-pop{50%{transform:translateY(-2px) scale(1.06);filter:brightness(1.08)}}</style>');
const date = (value) => new Intl.DateTimeFormat('cs-CZ', { dateStyle: 'medium' }).format(new Date(value));
document.querySelector('#users').closest('table').querySelector('thead tr').insertAdjacentHTML('beforeend', '<th>Akce</th>');
async function request(url, options) { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error); return data; }
async function load() { try { const me = await request('/api/me'); if (me.user.role !== 'admin') throw new Error('Bez přístupu'); const orders = await request('/api/orders'); document.querySelector('#orders').innerHTML = orders.orders.length ? orders.orders.map((order) => `<article class="order"><div class="order-top"><span>${escapeHtml(order.service)}</span>${status(order.status)}</div><p>${escapeHtml(order.details)}</p><small>${escapeHtml(order.customer.email)} · ${date(order.createdAt)}</small></article>`).join('') : `<p class="lead">${text('Zatím žádné objednávky.', 'No orders yet.')}</p>`; const users = await request('/api/admin/users'); document.querySelector('#users').innerHTML = users.users.map((user) => `<tr><td>${escapeHtml(user.email)}</td><td>${escapeHtml(user.role)}</td><td>${date(user.createdAt)}</td><td>${user.id === me.user.id ? text('Aktuální účet', 'Current account') : `<button type="button" data-user-id="${escapeHtml(user.id)}" data-user-email="${escapeHtml(user.email)}">${text('Odstranit', 'Delete')}</button>`}</td></tr>`).join(''); } catch { window.location.href = 'auth.html'; } }
document.querySelector('#logout').addEventListener('click', async () => { await fetch('/api/logout', { method:'POST' }); window.location.href = 'index.html'; });
document.querySelector('#users').addEventListener('click', async (event) => { const button = event.target.closest('[data-user-id]'); if (!button || !confirm(`Opravdu chcete odstranit účet ${button.dataset.userEmail}? Smažou se i všechny jeho objednávky.`)) return; try { await request(`/api/admin/users/${encodeURIComponent(button.dataset.userId)}`, { method:'DELETE' }); await load(); } catch (error) { alert(error.message); } });
load();
